server:
  port: 8761

spring:
  security:
    user:
      name: admin
      password: admin
  application:
    name: SSOEurekaServer


eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone:  http://admin:admin@localhost:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
